#!/bin/bash
# OpenSentry Command Center - Quick Setup Script
# Run: chmod +x setup.sh && ./setup.sh

set -e

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║         OpenSentry Command Center - Quick Setup               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Check for Docker
if ! command -v docker &> /dev/null; then
    echo "❌ Docker not found. Please install Docker first:"
    echo "   curl -fsSL https://get.docker.com | sh"
    exit 1
fi

echo "✅ Docker found"

# Check if .env exists
if [ -f .env ]; then
    echo "✅ .env file already exists"
    read -p "   Overwrite with new settings? (y/N): " overwrite
    if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
        echo "   Keeping existing .env"
        echo ""
        echo "🚀 Starting Command Center..."
        docker compose up --build -d
        echo ""
        echo "✅ Command Center is running!"
        echo "   Dashboard: http://localhost:5000"
        echo "   Logs: docker compose logs -f"
        exit 0
    fi
fi

echo ""
echo "📝 Let's configure your Command Center..."
echo ""

# Get username
read -p "Choose a username [admin]: " username
username=${username:-admin}

# Get password
while true; do
    read -s -p "Choose a password (min 8 chars): " password
    echo ""
    if [ ${#password} -lt 8 ]; then
        echo "   ❌ Password too short, try again"
    else
        break
    fi
done

# Generate secret
echo ""
echo "🔐 Generating security secret..."
secret=$(python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null || openssl rand -hex 32)

# Create .env file
cat > .env << EOF
# OpenSentry Command Center Configuration
# Generated by setup.sh on $(date)

# Login credentials
OPENSENTRY_USERNAME=$username
OPENSENTRY_PASSWORD=$password

# Security secret (share this with your Camera Nodes)
OPENSENTRY_SECRET=$secret

# Session timeout in minutes
SESSION_TIMEOUT=30
EOF

echo "✅ Configuration saved to .env"
echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  IMPORTANT: Copy this secret to your Camera Nodes!            ║"
echo "╠═══════════════════════════════════════════════════════════════╣"
echo "║  OPENSENTRY_SECRET=$secret"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Start the service
echo "🚀 Starting Command Center..."
docker compose up --build -d

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                    Setup Complete!                            ║"
echo "╠═══════════════════════════════════════════════════════════════╣"
echo "║  Dashboard:  http://localhost:5000                            ║"
echo "║  Username:   $username"
echo "║  Password:   ********                                         ║"
echo "╠═══════════════════════════════════════════════════════════════╣"
echo "║  Commands:                                                    ║"
echo "║    View logs:    docker compose logs -f                       ║"
echo "║    Stop:         docker compose down                          ║"
echo "║    Restart:      docker compose restart                       ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
